---
title: "Distribuição de probabilidade"

author: "Ana Flavia Machado Muniz Andrade"
date: '2022-05-04'
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introdução

### **Espaço Amostral**
  
  - É o conjunto formado por todos os resultados possíveis de um experimento aleatório. Em outras palavras, é o conjunto formado por todos os pontos amostrais de um experimento.Como por exemplo:
  
  Dado experimento "lançamento de um dado" o espaço amostral será: S={1, 2, 3, 4, 5, 6}.
  
  - Uma distribuição de probabilidade é um modelo matemático que relaciona um certo valor da variável em estudo com a sua probabilidade de ocorrência.Há dois tipos:
  
    - **Distribuições Contínuas**
    - **Distribuições Discretas**
    
## Distribuições Discretas

  - A probabilidade de que a variável  **X**  assuma um valor específico  x  é dada por:  P(**X** = x ) = P( x )
  
  - No caso de **variáveis contínuas**, as probabilidades são especificadas em termos de intervalos, pois a probabilidade associada a um número específico é zero (não enumerável).

### Distruinuição de Bernoulli

  - Este modelo probabilístico é caracterizado da seguinte forma:
  
  x=1 sucesso, P(x=1) = "p" (sucesso)
  
  x=0 fracasso, P(x=0) = 1 - p (fracasso)

  





## Slide with Bullets


## Slide with R Output



## Slide with Plot



